#!/bin/bash
apt-get update -qq

apt-get install --force-yes -y -qq wget php5-mysql apache2 libapache2-mod-fastcgi php5-fpm php5-gd php5-imap php5-mcrypt php5-xcache php5-mcrypt php5-imap php5-pgsql 

for script in `ls build.d/* | sort -V`; do echo Executing $script; chmod +x ./$script; ./$script; done

